In [42]:
df = pd.read_csv(
    r'C:\Users\DELL\Documents\MLOPS\Finance News Intelligent System\Financial-News-Intelligent-System---Enterprise-Level\artifacts\interim\news_data.csv'
)

In [45]:
df.columns

Index(['Unnamed: 0', 'ticker', 'title', 'summary', 'source', 'source_domain',
       'time_published', 'overall_sentiment_score', 'overall_sentiment_label'],
      dtype='object')

In [49]:
df.drop(columns=['source_domain', 'Unnamed: 0'], inplace=True, errors='ignore')

In [50]:
df.columns

Index(['ticker', 'title', 'summary', 'source', 'time_published',
       'overall_sentiment_score', 'overall_sentiment_label'],
      dtype='object')

In [51]:
df.shape

(462, 7)

# **Labelled_Data**

In [1]:
import pandas as pd

In [26]:
df = pd.read_csv(r"C:\Users\DELL\Documents\MLOPS\Finance News Intelligent System\Financial-News-Intelligent-System---Enterprise-Level\artifacts\interim\news_data.csv")

In [27]:
df.head()

,Unnamed: 0,ticker,title,summary,source,source_domain,time_published,overall_sentiment_score,overall_sentiment_label
0,0,AAPL,Consumer Discretionary Stocks Q3 Teardown: App...,This article provides a Q3 teardown of consume...,Finviz,Finviz,2026-01-04 22:34:00,0.273852,Somewhat-Bullish
1,1,AAPL,【即時新聞】FT Vest U.S. Equity Buffer & Premium Inc...,FT Vest U.S. Equity Buffer & Premium Income ET...,理財寶,理財寶,2026-01-04 22:09:17,0.061261,Neutral
2,2,AAPL,Apple stock heads into Monday under a valuatio...,Raymond James has initiated coverage on Apple ...,ts2.tech,ts2.tech,2026-01-04 21:55:33,0.084988,Neutral
3,3,AAPL,"At CES, Mercedes-Benz CLA Features Xperi Video...",Mercedes-Benz is showcasing its new CLA electr...,Radio World,Radio World,2026-01-04 18:08:56,0.201609,Somewhat-Bullish
4,4,AAPL,Apple stock starts 2026 on a slip as valuation...,Apple Inc. (AAPL.O) shares closed down 0.31% a...,ts2.tech,ts2.tech,2026-01-04 15:09:26,0.114468,Neutral

In [28]:
df.columns.tolist()

['Unnamed: 0',
 'ticker',
 'title',
 'summary',
 'source',
 'source_domain',
 'time_published',
 'overall_sentiment_score',
 'overall_sentiment_label']

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               462 non-null    int64
 1   ticker                   462 non-null    object
 2   title                    462 non-null    object
 3   summary                  462 non-null    object
 4   source                   462 non-null    object
 5   source_domain            462 non-null    object
 6   time_published           462 non-null    object
 7   overall_sentiment_score  462 non-null    float64
 8   overall_sentiment_label  462 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 32.6+ KB

In [30]:
df['ticker'].unique()

array(['AAPL', 'AMZN', 'MSFT', 'GOOGL', 'NVDA', 'META', 'TSLA', 'JPM',
       'V', 'JNJ', 'BAC', 'WMT', 'UNH', 'XOM', 'CVX'], dtype=object)

In [34]:
df.drop(columns=['source_domain'], inplace=True)

In [38]:
df['time_published'] = pd.to_datetime(df['time_published'])

In [43]:
start = df['time_published'].min()
end = df['time_published'].max()
print(f"Start: {start}, End: {end}")

Start: 2025-01-10 18:24:00, End: 2026-01-04 23:41:00

In [77]:
for i in range(325,462):
    print(df['time_published'].iloc[i])

2025-03-12 00:00:00
2025-03-11 00:00:00
2025-03-07 16:51:00
2025-03-07 14:10:00
2025-03-07 10:32:00
2025-03-06 08:59:00
2025-03-06 03:31:54
2025-03-31 11:39:50
2025-03-31 03:14:37
2025-03-31 02:09:50
2025-03-28 22:09:18
2025-03-28 15:23:00
2025-03-28 03:55:38
2025-03-28 03:44:32
2025-03-27 09:15:00
2025-03-26 07:00:00
2025-03-21 03:51:22
2025-03-20 16:05:00
2025-03-20 14:09:35
2025-03-20 03:51:32
2025-03-19 00:00:00
2025-03-18 02:37:01
2025-03-17 11:10:00
2025-03-31 03:12:44
2025-03-31 03:01:28
2025-03-30 18:10:43
2025-03-30 09:50:00
2025-03-29 08:55:00
2025-03-27 21:20:00
2025-03-27 03:55:02
2025-03-26 12:00:00
2025-03-26 02:33:03
2025-03-25 22:52:27
2025-03-24 22:11:01
2025-03-21 18:09:12
2025-03-21 13:39:00
2025-03-21 05:09:25
2025-03-21 19:16:00
2025-03-14 17:14:00
2025-03-11 10:54:00
2025-03-04 17:34:00
2025-02-18 05:11:39
2025-02-18 05:05:26
2025-02-03 05:15:11
2025-02-03 04:38:40
2025-01-31 22:09:14
2025-01-27 00:00:00
2025-01-24 15:34:00
2025-01-19 07:39:00
2025-01-13 10:16:00
2025-01-13 05:45:00
2025-01-10 18:24:00
2025-03-31 09:52:30
2025-03-31 03:12:41
2025-03-28 20:14:00
2025-03-27 03:07:36
2025-03-24 05:57:36
2025-03-24 03:12:41
2025-03-21 20:58:00
2025-03-21 17:11:00
2025-03-21 11:29:00
2025-03-21 07:48:00
2025-03-21 03:12:41
2025-03-21 00:00:00
2025-03-21 00:00:00
2025-03-21 00:00:00
2025-03-21 00:00:00
2025-03-17 16:15:00
2025-03-17 00:00:00
2025-03-14 03:14:54
2025-03-13 03:14:54
2025-03-12 17:15:00
2025-03-12 13:24:00
2025-03-31 02:35:11
2025-03-24 15:54:00
2025-03-24 09:30:00
2025-03-21 10:41:00
2025-03-19 13:27:00
2025-03-12 02:35:16
2025-03-11 15:56:00
2025-03-11 07:19:00
2025-03-06 04:46:00
2025-03-26 04:58:00
2025-03-24 10:17:00
2025-03-21 03:37:50
2025-03-20 03:55:21
2025-03-20 03:50:17
2025-03-20 03:22:00
2025-03-19 03:55:21
2025-03-14 03:55:22
2025-03-13 08:36:00
2025-03-13 05:10:26
2025-03-09 02:50:43
2025-03-06 10:15:00
2025-03-27 11:00:00
2025-03-27 09:29:00
2025-03-26 02:50:36
2025-03-20 09:23:00
2025-03-18 02:31:36
2025-03-14 03:33:03
2025-03-12 03:52:42
2025-03-12 03:08:58
2025-03-06 17:24:00
2025-03-06 03:51:30
2025-03-06 03:00:49
2025-03-04 17:38:00
2025-03-03 05:00:00
2025-03-02 03:52:42
2025-02-27 05:14:13
2025-02-25 05:14:13
2025-02-21 05:14:13
2025-02-21 04:32:22
2025-02-20 04:33:21
2025-02-19 04:33:21
2025-03-31 14:52:44
2025-03-24 12:46:00
2025-03-19 12:47:00
2025-03-19 11:18:00
2025-03-18 03:56:23
2025-03-17 23:08:00
2025-03-17 11:39:00
2025-03-11 11:09:30
2025-03-09 12:51:17
2025-03-01 03:56:23
2025-02-28 21:07:00
2025-03-31 02:50:58
2025-03-21 19:47:00
2025-03-20 04:24:00
2025-03-20 02:33:35
2025-03-17 03:08:00
2025-03-16 23:50:00
2025-03-12 02:50:58
2025-03-05 03:06:36
2025-03-04 03:03:57
2025-02-28 15:31:00
2025-02-27 01:33:00
2025-02-27 01:07:00

# **Impact Score**

In [119]:
df_ = pd.read_csv(r"C:\Users\DELL\Documents\MLOPS\Finance News Intelligent System\Financial-News-Intelligent-System---Enterprise-Level\artifacts\transform\impact_score\impact_scores.csv")

In [120]:
len(df_.columns.tolist())

22

In [121]:
df_.columns.tolist()

['ticker',
 'time_published',
 'news_date',
 'effective_date',
 'day0_date',
 'day1_date',
 'day0_close_stock',
 'day1_close_stock',
 'stock_return',
 'spy_return',
 'abnormal_return',
 'ar_score',
 'sentiment_score',
 'category_score',
 'impact_score',
 'impact_tier',
 'impact_direction',
 'event_label',
 'title',
 'summary',
 'source',
 'overall_sentiment_label']

In [123]:
df_.day0_close_stock.isnull().sum()

np.int64(0)

In [106]:
df_.day0_close

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...
457    150.809998
458    152.000000
459    158.619995
460    156.669998
461    156.669998
Name: day0_close, Length: 462, dtype: float64

In [125]:
df_['event_label'].unique()

array(['Regulatory/Legal', 'Product Launch', 'Market Movement',
       'Earnings', 'Other', 'Merger/Acquisition', 'Economic Data',
       'Leadership Change', 'Fed Monetary Policy'], dtype=object)

In [128]:
df_.columns.tolist()

['ticker',
 'time_published',
 'news_date',
 'effective_date',
 'day0_date',
 'day1_date',
 'day0_close_stock',
 'day1_close_stock',
 'stock_return',
 'spy_return',
 'abnormal_return',
 'ar_score',
 'sentiment_score',
 'category_score',
 'impact_score',
 'impact_tier',
 'impact_direction',
 'event_label',
 'title',
 'summary',
 'source',
 'overall_sentiment_label']

In [129]:

print("Shape:", df_.shape)
print("\nDtypes:\n", df_.dtypes)
print("\nNulls:\n", df_.isnull().sum())
print("\nDuplicates:", df_.duplicated(subset=["ticker", "title", "time_published"]).sum())
print("\nUnique event_labels:", df_["event_label"].unique())
print("\nSentiment score range:", df_["sentiment_score"].min(), "→", df_["sentiment_score"].max())
print("\nSample:\n", df_.head(3).to_string())

Shape: (461, 22)

Dtypes:
 ticker                      object
time_published              object
news_date                   object
effective_date              object
day0_date                   object
day1_date                   object
day0_close_stock           float64
day1_close_stock           float64
stock_return               float64
spy_return                 float64
abnormal_return            float64
ar_score                   float64
sentiment_score            float64
category_score             float64
impact_score               float64
impact_tier                 object
impact_direction            object
event_label                 object
title                       object
summary                     object
source                      object
overall_sentiment_label     object
dtype: object

Nulls:
 ticker                     0
time_published             0
news_date                  0
effective_date             0
day0_date                  0
day1_date                  0
day0_close_stock           0
day1_close_stock           0
stock_return               0
spy_return                 0
abnormal_return            0
ar_score                   0
sentiment_score            0
category_score             0
impact_score               0
impact_tier                0
impact_direction           0
event_label                0
title                      0
summary                    0
source                     0
overall_sentiment_label    0
dtype: int64

Duplicates: 0

Unique event_labels: ['Regulatory/Legal' 'Product Launch' 'Market Movement' 'Earnings' 'Other'
 'Merger/Acquisition' 'Economic Data' 'Leadership Change'
 'Fed Monetary Policy']

Sentiment score range: 0.002296 → 0.829771

Sample:
   ticker             time_published   news_date effective_date   day0_date   day1_date  day0_close_stock  day1_close_stock  stock_return  spy_return  abnormal_return  ar_score  sentiment_score  category_score  impact_score impact_tier impact_direction       event_label                                                                               title                                                                                                                                                                                                                                                                                                                                                                                                                                                                            summary             source overall_sentiment_label
0   TSLA  2025-03-20 03:51:32+00:00  2025-03-20     2025-03-20  2025-03-20  2025-03-21        236.259995        248.710007      0.052696    0.000330         0.052366       1.0         0.534652            0.80        0.8337    Critical         Positive  Regulatory/Legal            Tesla Cybertruck recalled eighth time, exterior body panels can fall off  The Tesla Cybertruck has been recalled for the eighth time due to issues with its stainless steel exterior. Specifically, the cant rail trim pieces can detach, posing a hazard to other road users, a problem Tesla plans to fix using a different structural adhesive and a stud-welded reinforcement. Despite multiple recalls for various issues including accelerator pedals and inverter faults, Tesla reports no collisions or injuries related to this particular defect.  Green Car Reports                 Bearish
1    JNJ  2025-03-31 03:12:41+00:00  2025-03-31     2025-03-31  2025-03-31  2025-04-01        161.344620        149.095901     -0.075916    0.002824        -0.078740       1.0         0.793051            0.45        0.8108    Critical         Negative    Product Launch  Johnson & Johnson named to Fortune’s 2025 America’s Most Innovative Companies list        Johnson & Johnson has again been recognized on Fortune’s annual ranking of America’s Most Innovative Companies for 2025, marking its presence on the list every year since its inception in 2023. The company is the top-ranked healthcare company at number 13 on this year's list of 300. This recognition highlights Johnson & Johnson's commitment to innovation across product, process, and culture, driven by its dedication to tackling pressing health challenges.  Johnson & Johnson                 Bullish
2    UNH  2025-02-20 04:33:21+00:00  2025-02-20     2025-02-20  2025-02-20  2025-02-21        486.561798        451.698059     -0.071653   -0.017104        -0.054549       1.0         0.268189            0.80        0.7670    Critical         Negative  Regulatory/Legal              Oz pledges to divest from HCA Healthcare and UnitedHealth if confirmed                        Mehmet Oz, nominated to lead the Centers for Medicare and Medicaid Services, has committed to divesting his investments in various healthcare companies, including HCA Healthcare and United Health Group, if confirmed. These divestments would occur within 90 days of his confirmation. He also plans to resign from advisory roles and sell shares in other healthcare ventures, while retaining ownership in his cattle ranch and Turkish real estate.              Axios        Somewhat-Bullish

# **Clean**

In [5]:
import pandas as pd

In [10]:
data = pd.read_csv(r"C:\Users\DELL\Documents\MLOPS\Finance News Intelligent System\Financial-News-Intelligent-System---Enterprise-Level\artifacts\transform\impact_score\impact_scores.csv")

In [11]:
data.head()

,ticker,time_published,news_date,effective_date,day0_date,day1_date,day0_close_stock,day1_close_stock,stock_return,spy_return,...,sentiment_score,category_score,impact_score,impact_tier,impact_direction,event_label,title,summary,source,overall_sentiment_label
0,TSLA,2025-03-20 03:51:32+00:00,2025-03-20,2025-03-20,2025-03-20,2025-03-21,236.259995,248.710007,0.052696,0.000330,...,0.534652,0.80,0.8337,Critical,Positive,Regulatory/Legal,"Tesla Cybertruck recalled eighth time, exterio...",The Tesla Cybertruck has been recalled for the...,Green Car Reports,Bearish
1,JNJ,2025-03-31 03:12:41+00:00,2025-03-31,2025-03-31,2025-03-31,2025-04-01,161.344620,149.095901,-0.075916,0.002824,...,0.793051,0.45,0.8108,Critical,Negative,Product Launch,Johnson & Johnson named to Fortune’s 2025 Amer...,Johnson & Johnson has again been recognized on...,Johnson & Johnson,Bullish
2,UNH,2025-02-20 04:33:21+00:00,2025-02-20,2025-02-20,2025-02-20,2025-02-21,486.561798,451.698059,-0.071653,-0.017104,...,0.268189,0.80,0.7670,Critical,Negative,Regulatory/Legal,Oz pledges to divest from HCA Healthcare and U...,"Mehmet Oz, nominated to lead the Centers for M...",Axios,Somewhat-Bullish
3,TSLA,2025-03-20 14:09:35+00:00,2025-03-20,2025-03-20,2025-03-20,2025-03-21,236.259995,248.710007,0.052696,0.000330,...,0.407186,0.65,0.7643,Critical,Positive,Market Movement,Was Tesla key to ESG outperformance last year?,"In 2020, sustainable US stock funds significan...",Morningstar Australia,Bullish
4,TSLA,2025-03-21 03:51:22+00:00,2025-03-21,2025-03-21,2025-03-21,2025-03-24,248.710007,278.390015,0.119336,0.017908,...,0.187184,0.80,0.7468,High,Positive,Regulatory/Legal,CII Updates Reincorporation & Shareholder Voti...,The Council of Institutional Investors (CII) h...,Minerva-Manifest,Somewhat-Bearish